# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3443c00e2577237fc9a599088ae9ea7776044eaea437341ec1b0bbdc88230e8f98968f2a0d11b6f3c1256a71eb44d1e29609232d8156cd33902bee9cdbe5867b

test:
  secret_key_base: 55eec735cef889d3b12c613de09a81530e36567de11cb4ca4ab5a68849e5df1187fc4c5195c5776512442538563e7592aa3586785981ae2c8d091672b09b4a4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
